import style from "./Profile.module.css";
import ProfileBgImage from "./Components/ProfileBgImage/ProfileBgImage";
import ProfileImage from "./Components/ProfileImage/ProfileImage";
import UserDetails from "./Components/UserDetails/UserDetails";
import UserEducation from "./Components/UserEducation/UserEducation";
import ContactDetails from "./Components/ContactDetails/ContactDetails";
import WorkExperience from "./Components/WorkExperience/WorkExperience";
import PromotionalVideo from "./Components/PromotionalVideo/PromotionalVideo";
import ProfileSetting from "./Components/ProfileSetting/ProfileSetting";
import {
  get_User_By_UserName,
  get_User_Contact_Details,
  get_User_Education,
  get_User_projects,
  get_User_Work_Experience,
} from "@/lib/data/user";
import { Suspense } from "react";
import { redirect } from "next/navigation";
import Portfolio from "./Components/Portfolio/Portfolio";
import ImageDropperCropper from "@/Components/Miscellaneous/ImageDropperCropper/ImageDropperCropper";
import UserDetailsForm from "@/Components/Miscellaneous/Forms/UserDetailsForm/UserDetailsForm";
import UserEducationForm from "@/Components/Miscellaneous/Forms/UserEducationForm/UserEducationForm";
import UserExperienceForm from "@/Components/Miscellaneous/Forms/UserExperienceForm/UserExperienceForm";
import ContactDetailsForm from "@/Components/Miscellaneous/Forms/ContactDetailsForm/ContactDetailsForm";
import { GetSession } from "@/lib/utils/getSessionData";
import ProjectForm from "@/Components/Miscellaneous/Forms/ProjectForm/ProjectForm";
import UploadPromotionalVideo from "@/Components/Miscellaneous/UploadPromotionalVideo/UploadPromotionalVideo";


export const metadata = {
  title: "FracsNet - Profile Page",
  description: "Generated by create next app",
};


const ProfilePage = async ({ params, searchParams }) => {

  const { username } = params;
  const { update } = searchParams;

  let user = await get_User_By_UserName(username);
  user = JSON.parse(JSON.stringify(user))

  if (!user) {
    redirect("/");
  }

  let education = await get_User_Education(user._id);
  education = JSON.parse(JSON.stringify(education))

  let experience = await get_User_Work_Experience(user._id);
  experience = JSON.parse(JSON.stringify(experience))

  let contact = await get_User_Contact_Details(user._id);
  contact = JSON.parse(JSON.stringify(contact))

  let projects = await get_User_projects(user._id);
  projects = JSON.parse(JSON.stringify(projects))

  const loggedInUser = await GetSession();

  return (
    <>
      <section className={style.homePrivate} >
        <div className="wrapper-width">
          <div className={style.contentGrid}>
            <div className={style.leftContent}>
              {
                user?._id == loggedInUser?._id &&
                <>
                  {update === "profileImage" && <ImageDropperCropper imgType={"user-profile-img"} resource={user} />}
                  {update === "bgImage" && <ImageDropperCropper imgType={"user-cover-img"} resource={user} />}
                  {update === "userInfo" && <UserDetailsForm user={user} />}
                  {update === "promotional_video" && <UploadPromotionalVideo user={user} />}
                  {update === "education" && <UserEducationForm user={user} education={education} />}
                  {update === "experience" && <UserExperienceForm user={user} experience={experience}  />}
                  {update === "contact" && <ContactDetailsForm user={user} contact={contact} />}
                  {update === "portfolio" && <ProjectForm user={user} projects={projects} />}
                </>
              }

              <Suspense fallback={<>Loading settings...</>}>
                <ProfileSetting />
              </Suspense>

            </div>
            <div className={style.mainContent}>
              <div className={style.mainContentWrapper}>

                <Suspense fallback={<>Loading user...</>}>
                  <>
                    <div className={style.images}>
                      <ProfileBgImage user={user} />
                      <ProfileImage user={user} />
                    </div>
                    {user && <UserDetails user={user} />}
                    <PromotionalVideo user={user} />
                  </>
                </Suspense>

                <Suspense fallback={<>Loading education...</>}>
                  <UserEducation education={education} user={user} />
                </Suspense>


                <Suspense fallback={<>Loading experience...</>}>
                  <WorkExperience user={user} experience={experience} />
                </Suspense>

                <Suspense fallback={<>Loading contact...</>}>
                  <ContactDetails user={user} contact={contact} />
                </Suspense>

              </div>
            </div>
            <div className={style.rightContent}>

              <Portfolio user={user} projects={projects} />

              <div className={style.sponsered}>
                <h2 className="sectionHeading">Try premium FracsNet Today!</h2>
                <button className={style.btn}>Pricing</button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default ProfilePage