import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import AuthProvider from "./context/authProvider";
import HeaderV1 from "@/Components/HeaderV1/HeaderV1";
import HeaderV2 from "@/Components/HeaderV2/HeaderV2";
import { get_loggedIn_user } from "@/lib/data/user";
import { StateProvider } from "./context/State";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FracsNet - Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  let loggedInUser = await get_loggedIn_user()
  loggedInUser = JSON.parse(JSON.stringify(loggedInUser))


  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/jodit/4.2.10/jodit.min.css"
        />
      </head>
      <AuthProvider>
        <body className={inter.className}>
          <StateProvider>
            {
              loggedInUser?._id ? <HeaderV2 loggedInUser={loggedInUser} /> : <HeaderV1 />
            }
            {children}
            <Footer />
            <script src="//cdnjs.cloudflare.com/ajax/libs/jodit/4.2.10/jodit.min.js"></script>
          </StateProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
