import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import AuthProvider from "./context/authProvider";
import HeaderV2 from "@/Components/HeaderV2/HeaderV2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link
          rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/jodit/4.2.10/jodit.min.css"
        />
      </head>
      <AuthProvider>
        <body className={inter.className}>
            {/* <Header/> */}
            <HeaderV2/>
            {children}
            <Footer/>
            <script src="//cdnjs.cloudflare.com/ajax/libs/jodit/4.2.10/jodit.min.js"></script>
        </body>
      </AuthProvider>
    </html>
  );
}
